version: "3.9"
services:
  frontend:
    build: ./frontend/
    volumes: 
      - ./frontend/:/usr/src/app/
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    command: ["sh", "-c", "npm install && npm start"]
  flask:
    build: ./server/
    volumes: 
      - ./server/:/usr/src/app/
    command: ["python", "app.py"]
